/**
 * SRT parser — converts an external .srt file (generated by Whisper/Colab/etc.)
 * into SubtitleBlock[]. The user generates the .srt outside the app and either
 * pastes the text or uploads the file.
 */
import type { SubtitleBlock } from "@/lib/codesnap-types";

const TIMECODE_RE =
  /^(\d{1,2}):(\d{2}):(\d{2})[,.](\d{1,3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[,.](\d{1,3})/;

function tcToSeconds(h: string, m: string, s: string, ms: string): number {
  const msPadded = (ms + "000").slice(0, 3);
  return (
    parseInt(h, 10) * 3600 +
    parseInt(m, 10) * 60 +
    parseInt(s, 10) +
    parseInt(msPadded, 10) / 1000
  );
}

/**
 * Parses standard SRT text into SubtitleBlock[].
 *
 * Tolerates: BOM, CRLF, missing/duplicated indices, `.` instead of `,` in the
 * milliseconds separator, trailing whitespace, blocks separated by 1+ blank
 * lines, multi-line text (joined with a space).
 *
 * Throws if the input contains zero recognizable cues.
 */
export function parseSrt(srtText: string): SubtitleBlock[] {
  const cleaned = srtText.replace(/^\uFEFF/, "").replace(/\r\n?/g, "\n").trim();
  if (!cleaned) throw new Error("El SRT está vacío.");

  const chunks = cleaned.split(/\n{2,}/);
  const blocks: SubtitleBlock[] = [];

  for (const chunk of chunks) {
    const lines = chunk.split("\n").map(l => l.trim()).filter(Boolean);
    if (lines.length === 0) continue;

    // Skip optional numeric index line
    let i = 0;
    if (/^\d+$/.test(lines[0])) i = 1;

    if (i >= lines.length) continue;
    const tcMatch = lines[i].match(TIMECODE_RE);
    if (!tcMatch) continue;

    const startSec = tcToSeconds(tcMatch[1], tcMatch[2], tcMatch[3], tcMatch[4]);
    const endSec   = tcToSeconds(tcMatch[5], tcMatch[6], tcMatch[7], tcMatch[8]);
    const text = lines.slice(i + 1).join(" ").trim();
    if (!text) continue;

    blocks.push({ startSec, endSec: Math.max(endSec, startSec + 0.1), text });
  }

  if (blocks.length === 0) {
    throw new Error("No se encontraron bloques válidos. Revisá el formato SRT.");
  }

  // Ensure monotonic ordering (sort by start time, just in case)
  blocks.sort((a, b) => a.startSec - b.startSec);
  return blocks;
}
